// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgr6RbCE882QKGovIxTPuonia3J15N9jE',
    appId: '1:1048474285975:web:9411b71cdf09846039f6d2',
    messagingSenderId: '1048474285975',
    projectId: 'thoughtsapp-ccdfa',
    authDomain: 'thoughtsapp-ccdfa.firebaseapp.com',
    storageBucket: 'thoughtsapp-ccdfa.firebasestorage.app',
    measurementId: 'G-ZWLXYP8NH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Hwgsgk18bN7lmzX8g15zKJRBxJdD6t4',
    appId: '1:1048474285975:android:0118b0f0ed230cc439f6d2',
    messagingSenderId: '1048474285975',
    projectId: 'thoughtsapp-ccdfa',
    storageBucket: 'thoughtsapp-ccdfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpkDfr1XsN1s2WtdbtRrda-FkFN4oEM6s',
    appId: '1:1048474285975:ios:61755466d60a347739f6d2',
    messagingSenderId: '1048474285975',
    projectId: 'thoughtsapp-ccdfa',
    storageBucket: 'thoughtsapp-ccdfa.firebasestorage.app',
    iosBundleId: 'com.example.thoughts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpkDfr1XsN1s2WtdbtRrda-FkFN4oEM6s',
    appId: '1:1048474285975:ios:61755466d60a347739f6d2',
    messagingSenderId: '1048474285975',
    projectId: 'thoughtsapp-ccdfa',
    storageBucket: 'thoughtsapp-ccdfa.firebasestorage.app',
    iosBundleId: 'com.example.thoughts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgr6RbCE882QKGovIxTPuonia3J15N9jE',
    appId: '1:1048474285975:web:b28c512fdfccd21c39f6d2',
    messagingSenderId: '1048474285975',
    projectId: 'thoughtsapp-ccdfa',
    authDomain: 'thoughtsapp-ccdfa.firebaseapp.com',
    storageBucket: 'thoughtsapp-ccdfa.firebasestorage.app',
    measurementId: 'G-DP0PVHKY6W',
  );

}